/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as CreateMyLookRouteImport } from './routes/create-my-look'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RequestReceivedRouteImport } from './routes/request-received'
import { Route as DesignDesignIdRouteImport } from './routes/design.$designId'
import { Route as ProductProductIdRouteImport } from './routes/product.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateMyLookRoute = CreateMyLookRouteImport.update({
  id: '/create-my-look',
  path: '/create-my-look',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestReceivedRoute = RequestReceivedRouteImport.update({
  id: '/request-received',
  path: '/request-received',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignDesignIdRoute = DesignDesignIdRouteImport.update({
  id: '/design/$designId',
  path: '/design/$designId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/create-my-look': typeof CreateMyLookRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/request-received': typeof RequestReceivedRoute
  '/design/$designId': typeof DesignDesignIdRoute
  '/product/$productId': typeof ProductProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/create-my-look': typeof CreateMyLookRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/request-received': typeof RequestReceivedRoute
  '/design/$designId': typeof DesignDesignIdRoute
  '/product/$productId': typeof ProductProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/create-my-look': typeof CreateMyLookRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/request-received': typeof RequestReceivedRoute
  '/design/$designId': typeof DesignDesignIdRoute
  '/product/$productId': typeof ProductProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collections'
    | '/create-my-look'
    | '/messages'
    | '/profile'
    | '/request-received'
    | '/design/$designId'
    | '/product/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collections'
    | '/create-my-look'
    | '/messages'
    | '/profile'
    | '/request-received'
    | '/design/$designId'
    | '/product/$productId'
  id:
    | '__root__'
    | '/'
    | '/collections'
    | '/create-my-look'
    | '/messages'
    | '/profile'
    | '/request-received'
    | '/design/$designId'
    | '/product/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionsRoute: typeof CollectionsRoute
  CreateMyLookRoute: typeof CreateMyLookRoute
  MessagesRoute: typeof MessagesRoute
  ProfileRoute: typeof ProfileRoute
  RequestReceivedRoute: typeof RequestReceivedRoute
  DesignDesignIdRoute: typeof DesignDesignIdRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-my-look': {
      id: '/create-my-look'
      path: '/create-my-look'
      fullPath: '/create-my-look'
      preLoaderRoute: typeof CreateMyLookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-received': {
      id: '/request-received'
      path: '/request-received'
      fullPath: '/request-received'
      preLoaderRoute: typeof RequestReceivedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/$designId': {
      id: '/design/$designId'
      path: '/design/$designId'
      fullPath: '/design/$designId'
      preLoaderRoute: typeof DesignDesignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionsRoute: CollectionsRoute,
  CreateMyLookRoute: CreateMyLookRoute,
  MessagesRoute: MessagesRoute,
  ProfileRoute: ProfileRoute,
  RequestReceivedRoute: RequestReceivedRoute,
  DesignDesignIdRoute: DesignDesignIdRoute,
  ProductProductIdRoute: ProductProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
